stages:
  - "Unit"
  - "Build"
  - "Lint"

# Only build every commit on the master branch (pull requests on other branches are still built)
branches:
  only:
    - master

jobs:
  include:
    ### Back-end

    # Back-end unit tests
    #- stage: "Unit"
    #  name: "Unit test back-end"
    #  language: java
    #  jdk: openjdk11
    #  before_script:
    #    - cd back-end
    #  script:
    #    - mvn test
    
    # Back-end build test
    - stage: "Build"
      name: "Build back-end"
      language: java
      jdk: openjdk11
      before_script:
        - cd back-end
      script:
        - mvn package -DskipTests=true

    # Back-end lint test
    - stage: "Lint"
      name: "Lint back-end"
      language: java
      jdk: openjdk11
      before_script:
        - cd back-end
      script:
        - mvn ktlint:check


    ### Front-end

    # Front-end unit tests
    - stage: "Unit"
      name: "Unit test front-end"
      language: node_js
      node_js: 14
      before_script:
        - cd front-end
      script:
        - npm install
        - npm run test

    # Front-end build test
    - stage: "Build"
      name: "Build front-end"
      language: node_js
      node_js: 14
      before_script:
        - cd front-end
      script:
        - npm install
        - npm run build

    # Front-end lint test
    - stage: "Lint"
      name: "Lint front-end"
      language: node_js
      node_js: 14
      before_script:
        - cd front-end
      script:
        - npm install
        - npm run lint
