jobs:
  include:
    # Back-end with Java 11 test
    - stage: "Test"
      language: java
      jdk: openjdk11
      cache:
        directories:
          - $HOME/.m2
      before_script:
        - cd back-end
      script:
        - mvn test
    
    # Front-end with Node.js 12 test
    - stage: "Test"
      language: node_js
      node_js: 12
      before_script:
        - cd front-end
      script:
        - npm install
        - npm run test
    
    # Front-end with Node.js 14 test
    - stage: "Test"
      language: node_js
      node_js: 14
      before_script:
        - cd front-end
      script:
        - npm install
        - npm run test
      